version: '3'
services:
  api:
    build: .
    restart: unless-stopped
    command: npm run start
    container_name: api
    ports:
      - "3000:3000"
    environment:
      DB_URL: postgres://wmcmlcpa:E9Q5-WGLgmbf6Uims9rVr7hABeG4WGCD@lucky.db.elephantsql.com/wmcmlcpa
    networks:
      - app_network

  frontend:
    build: ./client
    restart: unless-stopped
    command: npm run dev
    container_name: frontend
    depends_on:
      - api
    ports:
      - "3001:3001"

    networks:
      - app_network

networks:
  app_network:


