version: '3'
services:
  db:
    image: postgres:15.1-alpine3.16
    restart: unless-stopped
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: delivery
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: